# Generated by Django 2.1.7 on 2019-03-22 02:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_post_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='training.Profile'),
        ),
        migrations.RemoveField(
            model_name='note',
            name='dutys',
        ),
        migrations.AddField(
            model_name='note',
            name='dutys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='training.Duty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 2, 42, 56, 466412, tzinfo=utc)),
        ),
    ]
